version: '3.8'
services:
  postgresql-local:
    container_name: postgres-database
    image: postgres:13.14-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_USER: 
      POSTGRES_DB: 
    networks:
      - pg-local-networks
    ports:
      - 5432:5432

  pg-admin-local:
    container_name: poesgres-admin-local
    image: elestio/pgadmin:REL-8_6
    environment:
      PGADMIN_DEFAULT_EMAIL: 
      PGADMIN_DEFAULT_PASSWORD: 
      PGADMIN_LISTEN_PORT: 5050
    networks:
      - pg-local-networks
    ports:
      - 5050:5050


networks:
  pg-local-networks:
