version: '3.8'
services:
  rode-battle-api:
    container_name: rode-battle-api-management
    image: ${DOCKER_HUB_URL}/rode-be-api:nightly
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_DEFAULT_PASSWORD: ${ADMIN_DEFAULT_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}
      FOLDER_TEMPLATE_ID: ${FOLDER_TEMPLATE_ID}
      FOLDER_ID: ${FOLDER_ID}
      FOLDER_TEAMS_EXCEL: ${FOLDER_TEAMS_EXCEL}
      SALT_ROUND: ${SALT_ROUND}