on:
  workflow_dispatch:

jobs:
  build:
    name: Build source code to Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: longthanhle1122
          password: Lethanhlong03
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: longthanhle1122/rode-be:latest

